import java.awt.*;
import java.util.*;
import java.applet.*;
import java.awt.event.*;
public class snakes_and_ladders_with_msg_box extends Applet implements KeyListener,ActionListener
{
	Button key;
	public void init() {
		key=new Button();
		key.addKeyListener((KeyListener) this);
		add(key);
	}
	
	public void paint(Graphics g)
	{
		this.setSize(2000,1100);
		////////////////////////////////////////////////////////
		this.setBackground(Color.black);
		int i=0,j=0,x=0,y=0;
		for(j=0;j<4;j++)
		{
			i=0;
			x=1020;
			y=y+100;
			do
			{
				g.setColor(Color.white);
				g.fillRect(x,y,100,100);
				x=x+100;
				g.setColor(Color.orange);
				g.fillRect(x,y,100,100);
				x=x+100;
				i++;
			}while(i<4);
			i=0;
			x=1020;
			y=y+100;
			do
			{
				g.setColor(Color.orange);
				g.fillRect(x,y,100,100);
				x=x+100;
				g.setColor(Color.white);
				g.fillRect(x,y,100,100);
				x=x+100;
				i++;
			}while(i<4);
		}
		
		g.setColor(Color.pink);
		g.fillRect(130,300,120,50);
		g.setColor(Color.BLACK);
		g.drawString("P1-LEFT ARROW",140,330);
		g.setColor(Color.white);
		g.fillRect(130,400,120,50);
		g.setColor(Color.BLACK);
		g.drawString("P2-RIGHT ARROW",140,430);
		g.setColor(Color.red);
		g.drawRect(1019,99,802,802);
		g.setColor(Color.red);
		g.drawRect(1020,100,800,800);
		g.setColor(Color.red);
		g.drawRect(1021,101,798,798);
		////////////////////////////////////////////////////////
			
		////////////////////----dice----////////////////////////
		g.setColor(Color.orange);
		g.drawRect(135,105,110,110);
		g.setColor(Color.orange);
		g.fillRect(140,110,100,100);			    
			switch(num)
			{
			     case 1 : g.setColor(Color.red);     
			              g.fillOval(165,135,50,50);
			              break;
			     case 2 : g.setColor(Color.red);	
					      g.fillOval(145,115,30,30);
					      g.setColor(Color.red);
					      g.fillOval(205,175,30,30);
					      break;
			     case 3 : g.setColor(Color.red);		
					      g.fillOval(145,115,30,30);        
				          g.setColor(Color.red);        
					      g.fillOval(175,145,30,30);
					      g.setColor(Color.red);		
					      g.fillOval(205,175,30,30);
					      break;
			     case 4 : g.setColor(Color.red);		
				          g.fillOval(145,115,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(205,175,30,30);
				          g.setColor(Color.red);		
				          g.fillOval(205,115,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(145,175,30,30);
				          break;
			     case 5 : g.setColor(Color.red);        
					      g.fillOval(175,145,30,30);
					      g.setColor(Color.red);		
				          g.fillOval(145,115,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(205,175,30,30);
				          g.setColor(Color.red);		
				          g.fillOval(205,115,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(145,175,30,30);
				          break;
			     case 6 : g.setColor(Color.red);		
				          g.fillOval(145,115,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(205,115,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(205,175,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(145,175,30,30);
				          g.setColor(Color.red);		
				          g.fillOval(145,145,30,30);		
				          g.setColor(Color.red);		
				          g.fillOval(205,145,30,30);			          
			}				
		    ////////////////--MB--/////////////////////
		    g.setColor(Color.yellow);
		    g.fillRect(275, 100, 700, 400);
		    g.setColor(Color.BLACK);
		    Font font = new Font ("TEXT", Font.BOLD, 50);
		    g.setFont (font);
		    g.drawString("MESSAGE BOX", 450, 150);
		    g.setColor(Color.black);
		    g.fillRect(275, 160, 700, 10);
		    ///////--number printing board--///////////
		    g.setColor(Color.red);
   	        g.drawString("1", 1035, 850);
   	        g.drawString("2", 1135, 850);
   	        g.drawString("3", 1235, 850);
   	        g.drawString("4", 1335, 850);
            g.drawString("5", 1435, 850);
            g.drawString("6", 1535, 850);
            g.drawString("7", 1635, 850);
            g.drawString("8", 1735, 850);
            g.drawString("9", 1035, 750);
   	        g.drawString("10", 1135, 750);
   	        g.drawString("11", 1235, 750);
   	        g.drawString("12", 1335, 750);
            g.drawString("13", 1435, 750);
            g.drawString("14", 1535, 750);
            g.drawString("15", 1635, 750);
            g.drawString("16", 1735, 750);
            g.drawString("17", 1035, 650);
   	        g.drawString("18", 1135, 650);
   	        g.drawString("19", 1235, 650);
   	        g.drawString("20", 1335, 650);
            g.drawString("21", 1435, 650);
            g.drawString("22", 1535, 650);
            g.drawString("23", 1635, 650);
            g.drawString("24", 1735, 650);
            g.drawString("25", 1035, 550);
   	        g.drawString("26", 1135, 550);
   	        g.drawString("27", 1235, 550);
   	        g.drawString("28", 1335, 550);
            g.drawString("29", 1435, 550);
            g.drawString("30", 1535, 550);
            g.drawString("31", 1635, 550);
            g.drawString("32", 1735, 550);
            g.drawString("33", 1035, 450);
   	        g.drawString("34", 1135, 450);
   	        g.drawString("35", 1235, 450);
   	        g.drawString("36", 1335, 450);
            g.drawString("37", 1435, 450);
            g.drawString("38", 1535, 450);
            g.drawString("39", 1635, 450);
            g.drawString("40", 1735, 450);
            g.drawString("41", 1035, 350);
   	        g.drawString("42", 1135, 350);
   	        g.drawString("43", 1235, 350);
   	        g.drawString("44", 1335, 350);
            g.drawString("45", 1435, 350);
            g.drawString("46", 1535, 350);
            g.drawString("47", 1635, 350);
            g.drawString("48", 1735, 350);
            g.drawString("49", 1035, 250);
   	        g.drawString("50", 1135, 250);
   	        g.drawString("51", 1235, 250);
   	        g.drawString("52", 1335, 250);
            g.drawString("53", 1435, 250);
            g.drawString("54", 1535, 250);
            g.drawString("55", 1635, 250);
            g.drawString("56", 1735, 250);
            g.drawString("57", 1035, 150);
   	        g.drawString("58", 1135, 150);
   	        g.drawString("59", 1235, 150);
   	        g.drawString("60", 1335, 150);
            g.drawString("61", 1435, 150);
            g.drawString("62", 1535, 150);
            g.drawString("63", 1635, 150);
            g.drawString("64", 1735, 150);
		    ///////////////////////////////////////////////////////
		    switch(p1)
		    {
		    case 1  :g.setColor(Color.magenta);
                     g.fillRect(1020, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 2  :g.setColor(Color.magenta);
                     g.fillRect(1120, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 3  :g.setColor(Color.magenta);
                     g.fillRect(1220, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 4  :g.setColor(Color.magenta);
		             g.fillRect(1520, 600, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
		             g.setColor(Color.green);
		             g.drawString("LADDER", 330, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("4 TO 22", 330, 350);
		             p1=22;
                     break;
		    case 5  :g.setColor(Color.magenta);
                     g.fillRect(1420, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 6  :g.setColor(Color.magenta);
                     g.fillRect(1520, 800, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 7  :g.setColor(Color.magenta);
                     g.fillRect(1620, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 8  :g.setColor(Color.magenta);
                     g.fillRect(1720, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 9  :g.setColor(Color.magenta);
		             g.fillRect(1420, 500, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
		             g.setColor(Color.green);
		             g.drawString("LADDER", 330, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("9 TO 29", 330, 350);
		             p1=29;
                     break;
		    case 10 :g.setColor(Color.magenta);
                     g.fillRect(1120, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 11 :g.setColor(Color.magenta);
                     g.fillRect(1220, 700, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 12 :g.setColor(Color.magenta);
                     g.fillRect(1320, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 13 :g.setColor(Color.magenta);
                     g.fillRect(1420, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 14 :g.setColor(Color.magenta);
                     g.fillRect(1520, 700, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 15 :g.setColor(Color.magenta);
                     g.fillRect(1620, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 16 :g.setColor(Color.magenta);
                     g.fillRect(1720, 700, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 17 :g.setColor(Color.magenta);
                     g.fillRect(1020, 600, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 18 :g.setColor(Color.magenta);
                     g.fillRect(1120, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 19 :g.setColor(Color.magenta);
                     g.fillRect(1220, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 20 :g.setColor(Color.magenta);
                     g.fillRect(1320, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 21 :g.setColor(Color.magenta);
                     g.fillRect(1420, 600, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 22 :g.setColor(Color.magenta);
                     g.fillRect(1520, 600, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 23 :g.setColor(Color.magenta);
                     g.fillRect(1620, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 24 :g.setColor(Color.magenta);
                     g.fillRect(1720, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 25 :g.setColor(Color.magenta);
                     g.fillRect(1020, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 26 :g.setColor(Color.magenta);
                     g.fillRect(1120, 500, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 27 :g.setColor(Color.magenta);
		             g.fillRect(1320, 300, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
		             g.setColor(Color.green);
		             g.drawString("LADDER", 330, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("27 TO 44", 330, 350);
		             p1=44;
                     break;
		    case 28 :g.setColor(Color.magenta);
                     g.fillRect(1320, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 29 :g.setColor(Color.magenta);
                     g.fillRect(1420, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 30 :g.setColor(Color.magenta);
                     g.fillRect(1520, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 31 :g.setColor(Color.magenta);
                     g.fillRect(1620, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 32 :g.setColor(Color.magenta);
                     g.fillRect(1720, 500, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 33 :g.setColor(Color.magenta);
                     g.fillRect(1020, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 34 :g.setColor(Color.magenta);
                     g.fillRect(1120, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 35 :g.setColor(Color.magenta);
                     g.fillRect(1220, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 36 :g.setColor(Color.magenta);
                     g.fillRect(1320, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 37 :g.setColor(Color.magenta);
                     g.fillRect(1420, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 38 :g.setColor(Color.magenta);
                     g.fillRect(1520, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 39 :g.setColor(Color.magenta);
                     g.fillRect(1620, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 40 :g.setColor(Color.magenta);
                     g.fillRect(1720, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 41 :g.setColor(Color.magenta);
                     g.fillRect(1020, 300, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 42 :g.setColor(Color.magenta);
		             g.fillRect(1220, 600, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
		             g.setColor(Color.RED);
		             g.drawString("SNAKE", 330, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("42 TO 19", 330, 350);
		             p1=19;
                     break;
		    case 43 :g.setColor(Color.magenta);
                     g.fillRect(1220, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 44 :g.setColor(Color.magenta);
                     g.fillRect(1320, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 45 :g.setColor(Color.magenta);
                     g.fillRect(1420, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 46 :g.setColor(Color.magenta);
                     g.fillRect(1520, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 47 :g.setColor(Color.magenta);
                     g.fillRect(1620, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 48 :g.setColor(Color.magenta);
                     g.fillRect(1720, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 49 :g.setColor(Color.magenta);
                     g.fillRect(1020, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 50 :g.setColor(Color.magenta);
                     g.fillRect(1120, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 51 :g.setColor(Color.magenta);
                     g.fillRect(1220, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 52 :g.setColor(Color.magenta);
                     g.fillRect(1320, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 53 :g.setColor(Color.magenta);
                     g.fillRect(1420, 200, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 54 :g.setColor(Color.magenta);
		             g.fillRect(1620, 300, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
		             g.setColor(Color.RED);
		             g.drawString("SNAKE", 330, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("54 TO 47", 330, 350);
		             p1=47;
                     break;
		    case 55 :g.setColor(Color.magenta);
                     g.fillRect(1620, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 56 :g.setColor(Color.magenta);
                     g.fillRect(1720, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 57 :g.setColor(Color.magenta);
                     g.fillRect(1020, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 58 :g.setColor(Color.magenta);
                     g.fillRect(1120, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 59 :g.setColor(Color.magenta);
		             g.fillRect(1520, 400, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
		             g.setColor(Color.RED);
		             g.drawString("SNAKE", 330, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("59 TO 38", 330, 350);
		             p1=38;
                     break;
		    case 60 :g.setColor(Color.magenta);
                     g.fillRect(1320, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 61 :g.setColor(Color.magenta);
                     g.fillRect(1420, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 62 :g.setColor(Color.magenta);
                     g.fillRect(1520, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 63 :g.setColor(Color.magenta);
                     g.fillRect(1620, 100, 100, 100);
                     g.setColor(Color.yellow);
                     g.fillRect(620, 170, 10, 330);
                     g.setColor(Color.magenta);
                     g.drawString("Player-1", 320, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 300, 300);
                     break;
		    case 64 :g.setColor(Color.yellow);
		             g.fillRect(275, 170, 700, 330);		    	
		    	     g.setColor(Color.orange);
                     g.fillRect(1720, 110, 95, 90);
                     g.setColor(Color.red);
                     g.drawString("64", 1735, 150);
                     g.setColor(Color.blue);
                     g.drawString("Player-1 WON", 460, 320);
                     p1=0;
                     p2=0;
                     break;
            default :break;
		    }
		    switch(p2)
		    {
		    case 1  :g.setColor(Color.black);
                     g.fillRect(1020, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 2  :g.setColor(Color.black);
                     g.fillRect(1120, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 3  :g.setColor(Color.black);
                     g.fillRect(1220, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 4  :g.setColor(Color.black);
		             g.fillRect(1520, 600, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
		             g.setColor(Color.green);
		             g.drawString("LADDER", 730, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("4 TO 22", 730, 350);
		             p2=22;
                     break;
		    case 5  :g.setColor(Color.black);
                     g.fillRect(1420, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 6  :g.setColor(Color.black);
                     g.fillRect(1520, 800, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 7  :g.setColor(Color.black);
                     g.fillRect(1620, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 8  :g.setColor(Color.black);
                     g.fillRect(1720, 800, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 9  :g.setColor(Color.black);
		             g.fillRect(1420, 500, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
		             g.setColor(Color.green);
		             g.drawString("LADDER", 730, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("9 TO 29", 730, 350);
		             p2=29;
		    case 10 :g.setColor(Color.black);
                     g.fillRect(1120, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 11 :g.setColor(Color.black);
                     g.fillRect(1220, 700, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 12 :g.setColor(Color.black);
                     g.fillRect(1320, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 13 :g.setColor(Color.black);
                     g.fillRect(1420, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 14 :g.setColor(Color.black);
                     g.fillRect(1520, 700, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 15 :g.setColor(Color.black);
                     g.fillRect(1620, 700, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 16 :g.setColor(Color.black);
                     g.fillRect(1720, 700, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 17 :g.setColor(Color.black);
                     g.fillRect(1020, 600, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 18 :g.setColor(Color.black);
                     g.fillRect(1120, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 19 :g.setColor(Color.black);
                     g.fillRect(1220, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 20 :g.setColor(Color.black);
                     g.fillRect(1320, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 21 :g.setColor(Color.black);
                     g.fillRect(1420, 600, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 22 :g.setColor(Color.black);
                     g.fillRect(1520, 600, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 23 :g.setColor(Color.black);
                     g.fillRect(1620, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 24 :g.setColor(Color.black);
                     g.fillRect(1720, 600, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 25 :g.setColor(Color.black);
                     g.fillRect(1020, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 26 :g.setColor(Color.black);
                     g.fillRect(1120, 500, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 27 :g.setColor(Color.black);
		             g.fillRect(1320, 300, 100, 100);	
		             g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
		             g.setColor(Color.green);
		             g.drawString("LADDER", 730, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("27 TO 44", 730, 350);
		             p2=44;
                     break;
		    case 28 :g.setColor(Color.black);
                     g.fillRect(1320, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 29 :g.setColor(Color.black);
                     g.fillRect(1420, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 30 :g.setColor(Color.black);
                     g.fillRect(1520, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 31 :g.setColor(Color.black);
                     g.fillRect(1620, 500, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 32 :g.setColor(Color.black);
                     g.fillRect(1720, 500, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 33 :g.setColor(Color.black);
                     g.fillRect(1020, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 34 :g.setColor(Color.black);
                     g.fillRect(1120, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 35 :g.setColor(Color.black);
                     g.fillRect(1220, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 36 :g.setColor(Color.black);
                     g.fillRect(1320, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 37 :g.setColor(Color.black);
                     g.fillRect(1420, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 38 :g.setColor(Color.black);
                     g.fillRect(1520, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 39 :g.setColor(Color.black);
                     g.fillRect(1620, 400, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 40 :g.setColor(Color.black);
                     g.fillRect(1720, 400, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 41 :g.setColor(Color.black);
                     g.fillRect(1020, 300, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 42 :g.setColor(Color.black);
		             g.fillRect(1220, 600, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
		             g.setColor(Color.red);
		             g.drawString("SNAKE", 730, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("42 TO 19", 730, 350);
		             p2=19;
                     break;
		    case 43 :g.setColor(Color.black);
                     g.fillRect(1220, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 44 :g.setColor(Color.black);
                     g.fillRect(1320, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 45 :g.setColor(Color.black);
                     g.fillRect(1420, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 46 :g.setColor(Color.black);
                     g.fillRect(1520, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 47 :g.setColor(Color.black);
                     g.fillRect(1620, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 48 :g.setColor(Color.black);
                     g.fillRect(1720, 300, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 49 :g.setColor(Color.black);
                     g.fillRect(1020, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 50 :g.setColor(Color.black);
                     g.fillRect(1120, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 51 :g.setColor(Color.black);
                     g.fillRect(1220, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 52 :g.setColor(Color.black);
                     g.fillRect(1320, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 53 :g.setColor(Color.black);
                     g.fillRect(1420, 200, 100, 100);	
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 54 :g.setColor(Color.black);
		             g.fillRect(1620, 300, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
		             g.setColor(Color.red);
		             g.drawString("SNAKE", 730, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("54 TO 47", 730, 350);
		             p2=47;
                     break;
		    case 55 :g.setColor(Color.black);
                     g.fillRect(1620, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 56 :g.setColor(Color.black);
                     g.fillRect(1720, 200, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 57 :g.setColor(Color.black);
                     g.fillRect(1020, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 58 :g.setColor(Color.black);
                     g.fillRect(1120, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 59 :g.setColor(Color.black);
		             g.fillRect(1520, 400, 100, 100);
		             g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
		             g.setColor(Color.red);
		             g.drawString("SNAKE", 730, 290);
		             g.setColor(Color.LIGHT_GRAY);
		             g.drawString("59 TO 38", 730, 350);
		             p2=38;
                     break;
		    case 60 :g.setColor(Color.black);
                     g.fillRect(1320, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 61 :g.setColor(Color.black);
                     g.fillRect(1420, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 62 :g.setColor(Color.black);
                     g.fillRect(1520, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 63 :g.setColor(Color.black);
                     g.fillRect(1620, 100, 100, 100);
                     g.setColor(Color.magenta);
                     g.drawString("Player-2", 720, 220);
                     g.setColor(Color.pink);
                     g.drawString("PROCEED", 700, 300);
                     break;
		    case 64 :g.setColor(Color.yellow);
		             g.fillRect(275, 170, 700, 330);
		             g.setColor(Color.orange);
                     g.fillRect(1720, 110, 95, 90);
                     g.setColor(Color.red);
                     g.drawString("64", 1735, 150);
                     g.setColor(Color.blue);
                     g.drawString("Player-2 WON", 460, 320);
                     p1=0;
                     p2=0;
                     break;
            default :break;
		    }
		    
	}

	public static int dicex()
	{
		int num=0;
		Random dice = new Random();
		num=(1+dice.nextInt(6));
		return num;
	}
	
	@Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		
	}
	//////global variables////
    int num;
    int p1;
    int p2;
    /////////////////////////
	@Override
	public void keyPressed(KeyEvent e) {
		// TODO Auto-generated method stub
		switch(e.getKeyCode()){
		case KeyEvent.VK_LEFT:
			num=dicex();
			if((p1+num)<=64)
			{
				p1=p1+num;
			}
			break;
		case KeyEvent.VK_RIGHT:
			num=dicex();
			if((p2+num)<=64)
		    {
				p2=p2+num;
		    }
			
		}
		repaint();
	}
	@Override
	public void keyReleased(KeyEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void keyTyped(KeyEvent arg0) {
		// TODO Auto-generated method stub
		
	}
	public boolean action(Event ev,Object ob) {
		repaint();
		return true;
	}
}